stock_update:
    path: /fr/module/royergestionstocks/webservice
    controller: App\Controller\StockController::update

controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

